cmake_minimum_required(VERSION 3.18)
project(ssb_gazebo LANGUAGES CXX)
if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
  set(CMAKE_BUILD_TYPE RelWithDebInfo CACHE STRING "Build type" FORCE)
endif()
set(CMAKE_CXX_STANDARD 17)

find_package(ament_cmake REQUIRED)
find_package(ssb_core REQUIRED)
find_package(gz_sim_vendor REQUIRED)
find_package(gz-sim8 REQUIRED)
find_package(gz_plugin_vendor REQUIRED)
find_package(gz-plugin2 REQUIRED COMPONENTS register)
find_package(gz_transport_vendor REQUIRED)
find_package(gz-transport13 REQUIRED)
find_package(gz_gui_vendor REQUIRED)
find_package(gz-gui8 REQUIRED)
find_package(gz_rendering_vendor REQUIRED)
find_package(gz-rendering8 REQUIRED)
find_package(gz-rendering8-ogre2 REQUIRED)
find_package(gz_ogre_next_vendor REQUIRED)
find_package(PkgConfig REQUIRED)
pkg_check_modules(OGRE_NEXT REQUIRED IMPORTED_TARGET OGRE-Next)
find_package(Qt5 REQUIRED COMPONENTS Quick)
set(CMAKE_AUTORCC ON)
if(NOT CUDAToolkit_ROOT AND EXISTS "/usr/local/cuda")
  set(CUDAToolkit_ROOT "/usr/local/cuda")
endif()
find_package(CUDAToolkit REQUIRED)

add_library(ssb_gazebo_scan SHARED src/scan_system.cpp src/contact_system.cpp)
target_compile_options(ssb_gazebo_scan PRIVATE -Wall -Wextra)
target_link_libraries(ssb_gazebo_scan ssb_core::ssb_core gz-sim8::gz-sim8 gz-plugin2::register gz-transport13::gz-transport13)
install(TARGETS ssb_gazebo_scan DESTINATION lib)
add_library(SsbLightGlare SHARED gui/SsbLightGlare.cpp gui/SsbLightGlare.qrc)
set_target_properties(SsbLightGlare PROPERTIES AUTOMOC ON)
target_compile_options(SsbLightGlare PRIVATE -Wall -Wextra)
target_link_libraries(SsbLightGlare PRIVATE gz-gui8::gz-gui8
  gz-rendering8::gz-rendering8 gz-plugin2::register Qt5::Quick)
install(TARGETS SsbLightGlare LIBRARY DESTINATION lib)
add_library(SsbShadowSettings SHARED gui/SsbShadowSettings.cpp gui/SsbShadowSettings.qrc)
target_compile_options(SsbShadowSettings PRIVATE -Wall -Wextra)
target_link_libraries(SsbShadowSettings PRIVATE gz-gui8::gz-gui8
  gz-rendering8::gz-rendering8-ogre2 PkgConfig::OGRE_NEXT gz-transport13::gz-transport13 gz-plugin2::register Qt5::Quick)
install(TARGETS SsbShadowSettings LIBRARY DESTINATION lib)
install(DIRECTORY worlds DESTINATION share/${PROJECT_NAME})
if(BUILD_TESTING)
  find_package(ament_cmake_gtest REQUIRED)
  ament_add_gtest(test_control test/test_control.cpp)
  target_include_directories(test_control PRIVATE src)
  target_link_libraries(test_control ssb_core::ssb_timing gz-sim8::gz-sim8)
endif()
ament_package()
