cmake_minimum_required(VERSION 3.18)
project(ssb_gazebo LANGUAGES CXX)
if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
  set(CMAKE_BUILD_TYPE RelWithDebInfo CACHE STRING "Build type" FORCE)
endif()
set(CMAKE_CXX_STANDARD 17)

find_package(ament_cmake REQUIRED)
find_package(ssb_core REQUIRED)
find_package(gz_sim_vendor REQUIRED)
find_package(gz-sim8 REQUIRED)
find_package(gz_plugin_vendor REQUIRED)
find_package(gz-plugin2 REQUIRED COMPONENTS register)
if(NOT CUDAToolkit_ROOT AND EXISTS "/usr/local/cuda")
  set(CUDAToolkit_ROOT "/usr/local/cuda")
endif()
find_package(CUDAToolkit REQUIRED)

add_library(ssb_gazebo_scan SHARED src/scan_system.cpp src/contact_system.cpp)
target_compile_options(ssb_gazebo_scan PRIVATE -Wall -Wextra)
target_link_libraries(ssb_gazebo_scan ssb_core::ssb_core gz-sim8::gz-sim8 gz-plugin2::register)
install(TARGETS ssb_gazebo_scan DESTINATION lib)
install(DIRECTORY worlds DESTINATION share/${PROJECT_NAME})
ament_package()
