from setuptools import setup

setup(
    name='ssb_tools',
    version='0.1.0',
    packages=['ssb_tools'],
    data_files=[
        ('share/ament_index/resource_index/packages', ['resource/ssb_tools']),
        ('share/ssb_tools', ['package.xml']),
        ('share/ssb_tools/config', ['config/stage_b_scene.yaml', 'config/stage_b_material_set.yaml']),
        ('share/ssb_tools/tools', ['../../tools/ssb_runtime.sh', '../../tools/with_optix_runtime.sh',
                                   '../../tools/with_mesa_runtime.py']),
    ],
    install_requires=['setuptools'],
    zip_safe=True,
    maintainer='jerry',
    maintainer_email='dk.illidan@gmail.com',
    description='Independent references, reconstruction and validation for tunnel scan sessions.',
    license='Apache-2.0',
    tests_require=['pytest'],
    entry_points={'console_scripts': [
        'initial_unroll = ssb_tools.initial_unroll:main',
        'match_bands = ssb_tools.match_bands:main',
        'optimize_bands = ssb_tools.optimize_bands:main',
        'review_global_bands = ssb_tools.global_resample:main',
        'validate_stage_a = ssb_tools.validate_stage_a:main',
        'validate_stage_b_smoke = ssb_tools.validate_stage_b:main',
        'prepare_stage_b_scene = ssb_tools.stage_b_scene:main',
        'stage_b_materials = ssb_tools.stage_b_materials:main',
        'stage_b_cracks = ssb_tools.stage_b_cracks:main',
        'stage_b_surface = ssb_tools.stage_b_surface:main',
        'stage_b_runtime_surface = ssb_tools.stage_b_runtime_surface:main',
        'stage_b_tag_cracks = ssb_tools.stage_b_surface:tag_main',
        'stage_b_defects = ssb_tools.stage_b_defects:main',
        'stage_b_optics = ssb_tools.stage_b_optics:main',
    ]},
)
